### ISSUE TITLE
persistence of the glip-api.ai connection

### ISSUE THREAD

**Issue by saisub** [embbnux/glip-ai-bot#10]
Hi,
First of all thanks for your earlier help on getting the integration done. I now have the api.ai connector running on a google cloud engine running and everything seems to be working ok except that after a period of inactivity the bot stops responding to queries. The instance is still up and the server is running as far as I can tell. Any thoughts?

Thanks

Sai

**Comment by zengfenfei** [comment]
I think we can try upgrading the **ringcentral-ts** to the latest version.

**Comment by saisub** [comment]
I get this when I try
  Types of property 'save' are incompatible.
    Type '(token: Token) => void' is not assignable to type '(data: Token) => Promise<void>'.
      Type 'void' is not assignable to type 'Promise<void>'.
9 export default client.restoreToken(config.glipApp.account, store).catch(e => {
                        ~~~~~~~~~~~~
src/glip-auth.ts(9,23): error TS2339: Property 'restoreToken' does not exist on type 'RingCentral'.
29  let token = rc.rest.getToken();
                   ~~~~
src/rc-oauth.ts(29,17): error TS2339: Property 'rest' does not exist on type 'RingCentral'.
40  if (!rc || !rc.rest.getToken()) {
                   ~~~~
src/rc-oauth.ts(40,17): error TS2339: Property 'rest' does not exist on type 'RingCentral'.
84      await rc.restoreToken(null, new RedisTokenStore('rc-token:glip-user:' + creatorId, redis)).catch(e => {
                 ~~~~~~~~~~~~
src/rc-oauth.ts(84,12): error TS2339: Property 'restoreToken' does not exist on type 'RingCentral'.
54                      await sub.subscription.subscribeById(subscriptionId).catch(e => {
                                               ~~~~~~~~~~~~~
src/sms.ts(54,28): error TS2339: Property 'subscribeById' does not exist on type 'Subscription'.
169  if (!rc || !rc.rest.getToken()) {
                    ~~~~
src/sms.ts(169,17): error TS2339: Property 'rest' does not exist on type 'RingCentral'.

**Comment by saisub** [comment]
help now I cant run it at all :-(  It is failing to build

**Comment by saisub** [comment]
I was able to remove and rebuild to original version but will wait to try the new ringcentral-ts version until I hear from you as to what I am doing wrong

**Comment by zengfenfei** [comment]
I'll fix it soon

**Comment by saisub** [comment]
ok. Thanks. Let me know when you have done it and what I need to do then. Persumably re download the program and install

**Comment by embbnux** [comment]
hi, @saisub we have updated the code. Please pull code in our master branch, and `yarn install` to upgrade packages.
