### ISSUE TITLE
Trouble installing the bot

### ISSUE THREAD

**Issue by saisub** [embbnux/glip-ai-bot#9]
Here is the error message. Can you help?

C:\GLIP_BOT\glip-ai-bot-master-2\glip-ai-bot-master>npm start

> aibot@1.0.0 start C:\GLIP_BOT\glip-ai-bot-master-2\glip-ai-bot-master
> node build/index.js

Error SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\GLIP_BOT\glip-ai-bot-master-2\glip-ai-bot-master\node_modules\node-fetch\lib\body.js:48:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by embbnux** [comment]
Do you know which API youR app is requiring. You can check the raw data from API. I guess API server return you a HTML not JSON.

**Comment by saisub** [comment]
I am just trying to connect glip with API.AI and when I run it it dies =
at line **return JSON.parse(buffer.toString());**

in the function below. I tried adding JSON.stringify but that did not help either.  I am sending user name password etc to the glip server "server": "https://glip.devtest.ringcentral.com" and I think that's where it dies. Thanks for your help

Body.prototype.json = function() {

	// for 204 No Content response, buffer will be empty, parsing it will throw error
	if (this.status === 204) {
		return Body.Promise.resolve({});
	}

	return this._decode().then(function(buffer) {
	return JSON.parse(buffer.toString());
	});

};

**Comment by saisub** [comment]
If I print buffer to console.log. It looks something like this <Buffer 3c 21 64 6f............>

Thanks for your help

**Comment by saisub** [comment]
Looks like it is in hex. I am not trying to do anything new just connecting glip and API.AI is it possible that I have some error in my config file? It asks for glip app key and RC app key. As I understand they are both the same. Any pointers?

**Comment by saisub** [comment]
I tried it from a unix machine as well. Just to see if that was the problem. This is the error I am getting
Error { FetchError: invalid json response body at https://glip.devtest.ringcentral.com/404?url=%2Frestapi%2Foauth%2
Ftoken reason: Unexpected token < in JSON at position 0
    at /home/bharti/glip-ai-bot/node_modules/node-fetch/lib/body.js:48:31
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'FetchError',
  message: 'invalid json response body at https://glip.devtest.ringcentral.com/404?url=%2Frestapi%2Foauth%2Ftoken r
eason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }

**Comment by saisub** [comment]
I was able to see a string version of the buffer. Looks something like this
<!doctype html>
<html>
<head>
        <title>Glip &times; Not Found</title>
        <link rel="icon" image="image/x-icon" href="https://d2rbro28ib85bu.cloudfront.net/icons/favicon-orange-blue2.ico" />
        <script type="text/javascript" src="//use.typekit.net/kde5nht.js"></script>
        <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
        <style type="text/css">
                body {
                        background-color: #0c5483;
                        font-family: "proxima-nova", "Helvetica Neue", HelveticaNeue, Helvetica, Arial, sans-serif;
                        text-rendering: optimizeLegibility;
                        -webkit-font-smoothing: antialiased;
                }

                .relative {
                        position: relative;
                }

                .content {
                        left: 50%;
                        margin: -108px 0 0 -245px;
                        max-width: 700px;
                        position: absolute;
                        text-align: center;
                        top: 50%;
                        z-index: 9990;
                }

                .logo {
                        height: 64px;
                        left: 50%;
                        margin: -100px 0 0 -90px;
                        position: absolute;
                        width: 180px;
                }

                .logo.dark {
                        opacity: 0;
                }

                h1 {
                        color: #0584bd;
                        display: inline-block;
                        font-size: 500px;
                        font-weight: 600;
                        left: 50%;
                        line-height: 1;
                        margin: -250px 0 0 -454px;
                        position: absolute;
                        top: 50%;
                        z-index: 9000;
                }

                h2 {
                        border-bottom: 1px solid rgba(255,255,255, 0.25);
                        color: white;
                        font-size: 52px;
                        font-weight: 600;
                        margin: 0 0 30px 0;
                        padding-bottom: 20px;
                }

                p {
                        color: #d5f1c8;
                        font-size: 14px;
                        font-weight: 700;
                        letter-spacing: 4px;
                        margin-bottom: 40px;
                        text-transform: uppercase;
                }

                a {
                        background-color: rgba(255,255,255, 0.85);
                        color: #0584bd;
                        cursor: pointer;
                        display: inline-block;
                        font-size: 13px;
                        font-weight: 700;
                        height: 60px;
                        letter-spacing: 4px;
                        line-height: 60px;
                        outline: none;
                        padding: 0 100px;
                        text-decoration: none;
                        text-transform: uppercase;

                        -webkit-border-radius: 4px;
                        -moz-border-radius: 4px;
                        border-radius: 4px;
                }

                body, h1, h2, p, a, .logo {
                        -webkit-transition: all 0.2s;
                        -moz-transition: all 0.2s;
                        transition: all 0.2s;
                }

                body.hover {
                        background-color: white;
                }

                body.hover .logo.dark {
                        opacity: 1;
                }

                body.hover .logo.light {
                        opacity: 0;
                }

                body.hover h1 {
                        color: rgba(0,0,0, 0.03);
                }

                body.hover h2 {
                        border-color: rgba(0,0,0, 0.05);
                        color: #0584bd;
                }

                body.hover p {
                        color: #0584bd;
                }

                body.hover a {
                        background-color: #0584bd;
                        color: white;
                }
        </style>
</head>
<body id="404">
        <h1>404</h1>
        <div class="content">
                <div class="relative">
                        <img src="https://d2rbro28ib85bu.cloudfront.net/images/logo/logo_medium_light.png" class="logo light" width="424" height="150" />
                        <img src="https://d2rbro28ib85bu.cloudfront.net/images/logo/logo_medium_blue.png" class="logo dark" width="424" height="150" />
                        <h2>We couldn't find it.</h2>
                        <p>The page you're looking for doesn't exist.</p>
                        <a id="return_home" href="https://glip.com">Return Home</a>
                </div>
        </div>

        <script type="text/javascript">
                var el = document.getElementById("return_home");
                var body = document.getElementById("404");

                el.addEventListener('mouseover', function() {
                        body.className += ' hover';
                }, true);

                el.addEventListener('mouseout', function() {
                        body.className = body.className.replace('hover', '');
                }, true);
        </script>
</body>
</html>

**Comment by saisub** [comment]
I know the credentials work to log into glips devtest and the ringcentral devtest sites so this is something else. Any ideas?

**Comment by embbnux** [comment]
HI, @saisub I find you required a wrong api server. You need to update`glipApp.server`  to 'https://platform.devtest.ringcentral.com' in `config.json`. Glip api is provided by `https://platform.devtest.ringcentral.com`  if you use sandbox environment. And please use RingCentral Sandbox Account (phoneNumber, extension, password) to log in.

**Comment by saisub** [comment]
Thanks. I now have the server started. One more silly question. Hoe do I test it. I have an api.ai agent how do I test it inside glip? I went to the glip.devtest... but entering things there does not ping the api.ai agent. I am sure I am doing something silly. Any help would be appreciated

**Comment by saisub** [comment]
After the server ran for a while it threw up the following error ( not sure if it was because of anything I did on  Glip? I don't see any API.AI agent in GLIP --- unlike what I can see if slack when I do a one click integration from API.AI

(node:8236) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'replace' of undefined
(node:8236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by saisub** [comment]
On the unix machine I have it running but don't know how to test it. typing things on the glip platform does not seem to go to the api.ai engine and no errors either

**Comment by saisub** [comment]
I am trying to have all of my glip entries go to the API.ai engine to answer if there is a match

**Comment by embbnux** [comment]
Can you see any logs from here [L68](https://github.com/embbnux/glip-ai-bot/blob/master/src/index.ts#L68) to check you receive a glip message from `https://glip.devtest.ringcentral.com/`. You need to log in to `https://service.devtest.ringcentral.com` with your sandbox account to create a new extension. Then use this extension to login to `https://glip.devtest.ringcentral.com/`. So you can talk with your bot in glip sandbox env.
After you can receive your message in your bot server, please check the api.ai response by logging [apiRes](https://github.com/embbnux/glip-ai-bot/blob/master/src/index.ts#L69)

**Comment by saisub** [comment]
Thanks I got it to work in the sandbox. I can't seem to get it to graduate. It still says no tests done in glip/posts. glip/persons is ok but the glip/posts still has a red x on it

**Comment by embbnux** [comment]
Hi saisub. You can click analytics near to status to find which condition is not satisfied. It needs to call every endpoint that you have 5 times in 48 hours. And calls all permissions that you added.

**Comment by saisub** [comment]
Thanks for all your help. I got it working!!!

**Comment by embbnux** [comment]
Wonderful! Congratulation

**Comment by saisub** [comment]
Thanks
